In [4]:
import pandas as pd

In [5]:
train = pd.read_csv('traffic.csv')
train.head()

              DateTime  Junction  Vehicles           ID
0  2015-11-01 00:00:00         1        15  20151101001
1  2015-11-01 01:00:00         1        13  20151101011
2  2015-11-01 02:00:00         1        10  20151101021
3  2015-11-01 03:00:00         1         7  20151101031
4  2015-11-01 04:00:00         1         9  20151101041

In [6]:
# get date
def get_dom(dt):
    return dt.day

# get week day
def get_weekday(dt):
    return dt.weekday()

# get hour
def get_hour(dt):
    return dt.hour

# get year
def get_year(dt):
    return dt.year

# get month
def get_month(dt):
    return dt.month

# get year day
def get_dayofyear(dt):
    return dt.dayofyear

# get year week
def get_weekofyear(dt):
    return dt.weekofyear

train['DateTime'] = train['DateTime'].map(pd.to_datetime)
train['date'] = train['DateTime'].map(get_dom)
train['weekday'] = train['DateTime'].map(get_weekday)
train['hour'] = train['DateTime'].map(get_hour)
train['month'] = train['DateTime'].map(get_month)
train['year'] = train['DateTime'].map(get_year)
train['dayofyear'] = train['DateTime'].map(get_dayofyear)
train['weekofyear'] = train['DateTime'].map(get_weekofyear)

In [7]:
train = train.drop(['DateTime'], axis=1)

trainnig = train.drop(['Vehicles'], axis=1)

target = train['Vehicles']

In [8]:
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor()

In [ ]:
model.fit(trainnig,target)

In [11]:
trainnig

,Junction,ID,date,weekday,hour,month,year,dayofyear,weekofyear
0,1,20151101001,1,6,0,11,2015,305,44
1,1,20151101011,1,6,1,11,2015,305,44
2,1,20151101021,1,6,2,11,2015,305,44
3,1,20151101031,1,6,3,11,2015,305,44
4,1,20151101041,1,6,4,11,2015,305,44
...,...,...,...,...,...,...,...,...,...
48115,4,20170630194,30,4,19,6,2017,181,26
48116,4,20170630204,30,4,20,6,2017,181,26
48117,4,20170630214,30,4,21,6,2017,181,26
48118,4,20170630224,30,4,22,6,2017,181,26
48119,4,20170630234,30,4,23,6,2017,181,26

In [ ]:
model.predict([[1,20151101021,1,6,2,11,2015,305,44]])

**array([10.19])**